<a href="https://colab.research.google.com/github/Adarsha9845/Transmission-Line-Upgrade/blob/main/DataCleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
Path = "/content/drive/MyDrive/Dataset for EEE577/BranchData.xlsx"

In [3]:
df = pd.read_excel(Path)

In [4]:
df.head()

,ID,From Bus,From Bus Updated,To Bus,To Bus Updated,L Miles,Lambda P,Dur,Lambda t,R pu,X pu,B pu,Con MVA,LTE MVA,STE MVA,Tr PU
0,A1,101,1,102,2,3.0,0.24,16,0.0,0.003,0.014,0.461,175,193,200,0.0
1,A2,101,1,103,3,55.0,0.51,10,2.9,0.055,0.211,0.057,175,208,220,0.0
2,A3,101,1,105,5,22.0,0.33,10,1.2,0.022,0.085,0.023,175,208,220,0.0
3,A4,102,2,104,4,33.0,0.39,10,1.7,0.033,0.127,0.034,175,208,220,0.0
4,A5,102,2,106,6,50.0,0.48,10,2.6,0.050,0.192,0.052,175,208,220,0.0

In [5]:
bus_mapping = {**{i: i - 100 for i in range(101, 125)},
               **{i: i - 176 for i in range(201, 225)},
               **{i: i - 252 for i in range(301, 326)}}

# mapping technique
df['From Bus Updated'] = df['From Bus'].map(bus_mapping)
df['To Bus Updated'] = df['To Bus'].map(bus_mapping)

print(df)

        ID  From Bus  From Bus Updated  To Bus  To Bus Updated  L Miles  \
0       A1       101                 1     102               2      3.0
1       A2       101                 1     103               3     55.0
2       A3       101                 1     105               5     22.0
3       A4       102                 2     104               4     33.0
4       A5       102                 2     106               6     50.0
..     ...       ...               ...     ...             ...      ...
103  C25‑1       315                63     321              69     34.0
104  C25‑2       315                63     321              69     34.0
105    C26       315                63     324              72     36.0
106    C27       316                64     317              65     18.0
107    C28       316                64     319              67     16.0

     Lambda P  Dur  Lambda t   R pu   X pu   B pu  Con MVA  LTE MVA  STE MVA  \
0        0.24   16       0.0  0.003  0.014  0.461      175      193      200
1        0.51   10       2.9  0.055  0.211  0.057      175      208      220
2        0.33   10       1.2  0.022  0.085  0.023      175      208      220
3        0.39   10       1.7  0.033  0.127  0.034      175      208      220
4        0.48   10       2.6  0.050  0.192  0.052      175      208      220
..        ...  ...       ...    ...    ...    ...      ...      ...      ...
103      0.41   11       0.8  0.006  0.049  0.103      500      600      625
104      0.41   11       0.8  0.006  0.049  0.103      500      600      625
105      0.41   11       0.9  0.007  0.052  0.109      500      600      625
106      0.35   11       0.4  0.003  0.026  0.055      500      600      625
107      0.34   11       0.4  0.003  0.023  0.049      500      600      625

     Tr PU
0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
..     ...
103    0.0
104    0.0
105    0.0
106    0.0
107    0.0

[108 rows x 16 columns]

In [6]:
df.head(-5)

,ID,From Bus,From Bus Updated,To Bus,To Bus Updated,L Miles,Lambda P,Dur,Lambda t,R pu,X pu,B pu,Con MVA,LTE MVA,STE MVA,Tr PU
0,A1,101,1,102,2,3.0,0.24,16,0.0,0.003,0.014,0.461,175,193,200,0.0
1,A2,101,1,103,3,55.0,0.51,10,2.9,0.055,0.211,0.057,175,208,220,0.0
2,A3,101,1,105,5,22.0,0.33,10,1.2,0.022,0.085,0.023,175,208,220,0.0
3,A4,102,2,104,4,33.0,0.39,10,1.7,0.033,0.127,0.034,175,208,220,0.0
4,A5,102,2,106,6,50.0,0.48,10,2.6,0.050,0.192,0.052,175,208,220,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98,C20,312,60,313,61,33.0,0.40,11,0.8,0.006,0.048,0.100,500,600,625,0.0
99,C21,312,60,323,71,67.0,0.52,11,1.6,0.012,0.097,0.203,500,600,625,0.0
100,C22,313,61,323,71,60.0,0.49,11,1.5,0.011,0.087,0.182,500,600,625,0.0
101,C23,314,62,316,64,27.0,0.38,11,0.7,0.005,0.059,0.082,500,600,625,0.0
102,C24,315,63,316,64,12.0,0.33,11,0.3,0.002,0.017,0.036,500,600,625,0.0

In [7]:
df.iloc[75]

ID                  B32‑2
From Bus              219
From Bus Updated       43
To Bus                220
To Bus Updated         44
L Miles              27.5
Lambda P             0.38
Dur                    11
Lambda t              0.7
R pu                0.005
X pu                 0.04
B pu                0.083
Con MVA               500
LTE MVA               600
STE MVA               625
Tr PU                 0.0
Name: 75, dtype: object

In [8]:
df.to_excel(Path, index=False)

In [9]:
df = pd.read_excel('/content/drive/MyDrive/Dataset for EEE577/GenData.xlsx')

In [10]:
df.head(5)

   SN  BUS ID  Updated Bus Unit Type  ID  Vs PU
0   1     101          NaN       U20   1  1.035
1   2     101          NaN       U20   2  1.035
2   3     101          NaN       U76   3  1.035
3   4     101          NaN       U76   4  1.035
4   5     102          NaN       U20   1  1.035

In [11]:
bus_mapping = {**{i: i - 100 for i in range(101, 125)},
               **{i: i - 176 for i in range(201, 225)},
               **{i: i - 252 for i in range(301, 326)}}

# mapping technique
df['Updated Bus'] = df['BUS ID'].map(bus_mapping)

print(df)

    SN  BUS ID  Updated Bus Unit Type  ID  Vs PU
0    1     101            1       U20   1  1.035
1    2     101            1       U20   2  1.035
2    3     101            1       U76   3  1.035
3    4     101            1       U76   4  1.035
4    5     102            2       U20   1  1.035
..  ..     ...          ...       ...  ..    ...
94  95     322           70       U50   5  1.050
95  96     322           70       U50   6  1.050
96  97     323           71      U155   1  1.050
97  98     323           71      U155   2  1.050
98  99     323           71      U350   3  1.050

[99 rows x 6 columns]

In [12]:
df.to_excel('/content/drive/MyDrive/Dataset for EEE577/GenData.xlsx', index=False)